#!/bin/bash
/bin/rm -rf logs mav.tlog  mav.tlog.raw
export MASTER_DRONE=1
location=Moab
location=keywest
python3 ../Tools/autotest/sim_vehicle.py --map --console -L $location --instance=2

#python3 ../Tools/autotest/sim_vehicle.py --map --console -L $location --instance=1

#python3 ../Tools/autotest/sim_vehicle.py --map --console -L $location -I 2
#python3 ../Tools/autotest/sim_vehicle.py --instance=2 --map --console -L $location
#output add <ip-address>:14551

