#!/bin/bash
#export TETHER_KG_PER_METER=0
export TETHER_KG_PER_METER=.0238
location=keywest
location=PortHueneme
location=AustinRC
location=Moab
/bin/rm -rf logs mav.tlog  mav.tlog.raw /tmp/master-gps.data
#ulimit
python3 ../Tools/autotest/sim_vehicle.py --instance=0 --map --console -L $location -f hexa -D 
#python3 ../Tools/autotest/sim_vehicle.py --instance=0 --map --console -L $location -f hexa -D --gdb  #debugging 
#python3 ../Tools/autotest/sim_vehicle.py -M -f hexa --map --console -L $location -I 0
#python3 ../Tools/autotest/sim_vehicle.py --instance=0 --map --console -L $location -M  -f hexa
