#!/bin/bash
export TETHER_KG_PER_METER=0
export TETHER_KG_PER_METER=.0238
location=keywest
location=Moab
/bin/rm -rf logs mav.tlog  mav.tlog.raw /tmp/master-gps.data
python3 ../Tools/autotest/sim_vehicle.py --instance=0 --map --console -L $location -f hexa
#python3 ../Tools/autotest/sim_vehicle.py -M -f hexa --map --console -L $location -I 0
# -M turns gimbal status
#python3 ../Tools/autotest/sim_vehicle.py --instance=0 --map --console -L $location -M  -f hexa
